### ISSUE TITLE
[新手求指导]请问下有没有？Linux可以直接运行的文件？

### ISSUE THREAD

**Issue by Mr-huangyh** [claw6148/EsDialerGD#12]
请问下有没有？Linux可以直接运行的文件？
不过可能我们这的验证系统有点不同，我在响应列表里面没有看到有cgi结尾的请求
只有aspx、jsp和ashx的请求
软件：
Windos版本：http://zsteduapp.10000.gd.cn/EsurfingClient/GetClient.aspx?areaCode=gd&osType=windows&dialType=portal

Macos版本：http://zsteduapp.10000.gd.cn/EsurfingClient/GetClient.aspx?areaCode=gd&osType=macos&dialType=portal

**Comment by claw6148** [comment]
没有。不想引入二进制兼容的问题，不同版本不同架构能编译一堆。
客户端跟我这里的一样

**Comment by Mr-huangyh** [comment]
但是我没有看到拉回请求，请问下，还有什么抓包的方法吗？

**Comment by claw6148** [comment]
wireshark
