### ISSUE TITLE
算法貌似更新了

### ISSUE THREAD

**Issue by TheSmallMain** [claw6148/EsDialerGD#16]
解码的内容好像为空，请求更新一下~

**Comment by ftfuntjh** [comment]
新版MacOS拨号程序用VMP加壳了。 怕是凉凉的感觉

**Comment by claw6148** [comment]
拿我的代码套壳去卖就没意思了兄弟。

**Comment by ftfuntjh** [comment]
额 我是说我们学校的天翼校园更新了。新的版本加了VMP的壳。= =你需要样本的话我可以发你一份。

**Comment by ftfuntjh** [comment]
好像VMP的版本是3.x的。
