### ISSUE TITLE
客户端ID冲突问题

### ISSUE THREAD

**Issue by TheSmallMain** [claw6148/EsDialerGD#5]
我们同宿舍的测试，登陆好像是可以的，但是发送keep请求时会出现冲突问题，一台计算机KEEP后另一台计算机就无法KEEP，请问如何解决。

**Comment by claw6148** [comment]
看来客户端id可能是全局唯一的。目前随机生成的话有几率会失败，还在研究id的生成算法。先抓包把本机的客户端id找到，替换程序里的那一串吧 :)

**Comment by TheSmallMain** [comment]
非常感谢！
如果客户端ID是唯一的话，我觉得可能是某个地区内的唯一？
因为如果大家都使用这串2B2B......客户端ID的话，应该会一直发生冲突，但是经过几天测试下来，只要宿舍同学不使用，我这就不会发生错误。

**Comment by claw6148** [comment]
哈哈 也可能是这玩意还没啥人在用:)
