### ISSUE TITLE
目瞪狗呆的看了半天，不会用。。。

### ISSUE THREAD

**Issue by qingninglx** [claw6148/EsDialerGD#9]
大触可以弄简单点或者说的清楚些么  小白不太懂  百度也没找到怎么使用

**Comment by claw6148** [comment]
有编译好的二进制文件～见：https://github.com/claw6148/EsDialerGD/releases

**Comment by qingninglx** [comment]
由于找不到libgcc_s_s_dw2-1.dll,无法继续执行代码。重新安装程序可能回解决此问题。然后百度https://www.cnblogs.com/ziyu-trip/p/7762018.html这个解决方法也不行。是需要安装什么支持库么

**Comment by claw6148** [comment]
已更新release

**Comment by qingninglx** [comment]
感谢，已经成功。
